name: dockerize executor

on:
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # code checkout
      - name: checkout the code
        uses: actions/checkout@v4

      # docker login
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # build and push to docker
      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.executor
          push: true
          tags: smnthjm08/zapier-executor:${{ github.sha }}

        # TODO deploy to vm
